#!/bin/sh

# A sample docker-setup hook
#
# Sets up a Docker network which can then be used by the application’s containers

ssh root@$KAMAL_HOSTS 'mkdir -p /letsencrypt && touch /letsencrypt/acme.json && chmod 600 /letsencrypt/acme.json'
